swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all transactions for the current month
      security:
        - Bearer: []
      responses:
        '200':
          description: List of transactions for the current month
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
    post:
      tags:
        - Transactions Module
      summary: Add a new transaction
      parameters:
        - in: body
          name: body
          description: New transaction details
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      security:
        - Bearer: []
      responses:
        '201':
          description: Transaction created successfully
        '400':
          description: Invalid transaction details
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get details of a specific transaction
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Details of the transaction
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
    put:
      tags:
        - Transactions Module
      summary: Update a specific transaction
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Transaction details to update
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      security:
        - Bearer: []
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid transaction details
        '404':
          description: Transaction not found
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
        format: date-time
        description: Date of the transaction
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        format: float
        description: Transaction amount
      balance:
        type: number
        format: float
        description: Balance after the transaction
      type:
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      notes:
        type: string
        description: Additional notes about the transaction
